
DROP SEQUENCE PAYMENT_SEQ;
DROP SEQUENCE TOURIST_SEQ;
DROP SEQUENCE RESERVE_SEQ;

CREATE SEQUENCE RESERVE_SEQ NOCACHE;
CREATE SEQUENCE TOURIST_SEQ NOCACHE;
CREATE SEQUENCE PAYMENT_SEQ NOCACHE;

DROP TABLE PAYMENT_T;
DROP TABLE TOURIST_T;
DROP TABLE RESERVE_T;

CREATE TABLE RESERVE_T (
    RESERVE_NO     NUMBER             NOT NULL,  -- 예약번호(PK)
    RESERVED_AT    VARCHAR2(50 BYTE)  NOT NULL,  -- 예약일자
    REQUESTED_TERM VARCHAR2(200 BYTE) NULL,      -- 요청사항
    AGREE          NUMBER             NULL,      -- 약관동의여부 0:필수 1:선택
    DEPARTURE_LOC  VARCHAR2(50 BYTE)  NULL,      -- 출발지
    RESERVE_STATUS NUMBER             NULL,      -- 예약상태 0:대기 1:완료 2:취소
    RESERVE_START  VARCHAR2(30 BYTE)  NULL,      -- 예약일정 시작일
    RESERVE_FINISH VARCHAR2(30 BYTE)  NULL,      -- 예약일정 종료일   
    RESERVE_PERSON NUMBER             NULL,      -- 예약인원수
    RESERVE_PRICE  NUMBER             NULL,      -- 예약가격
    USER_NO        NUMBER             NOT NULL,  -- 회원번호(FK)
    PACKAGE_NO     NUMBER             NULL,      -- 패키지번호(FK)
    HOTEL_NO       NUMBER             NULL,      -- 호텔번호(FK)
    ROOM_NO        NUMBER             NULL,      -- 객실번호(FK)
    CONSTRAINT PK_RES       PRIMARY KEY(RESERVE_NO),
    CONSTRAINT FK_USER_RES  FOREIGN KEY(USER_NO)    REFERENCES USER_T(USER_NO) ON DELETE CASCADE,
    CONSTRAINT FK_PACK_RES  FOREIGN KEY(PACKAGE_NO) REFERENCES PACKAGE_T(PACKAGE_NO) ON DELETE SET NULL,
    CONSTRAINT FK_HOTEL_RES FOREIGN KEY(HOTEL_NO)   REFERENCES HOTEL_T(HOTEL_NO) ON DELETE SET NULL,
    CONSTRAINT FK_ROOM_RES  FOREIGN KEY(ROOM_NO)    REFERENCES ROOMTYPE_T(ROOM_NO) ON DELETE SET NULL
);

CREATE TABLE TOURIST_T (
    TOURIST_NO NUMBER            NOT NULL,  -- 여행객번호(PK)
    NAME       VARCHAR2(20 BYTE) NULL,      -- 여행객이름
    BIRTH_DATE VARCHAR2(30 BYTE) NULL,      -- 생년월일
    GENDER     VARCHAR2(2 BYTE)  NULL,      -- 성별
    MOBILE     VARCHAR2(15 BYTE) NULL,      -- 연락처
    AGE_CASE   NUMBER            NULL,      -- 연령대 0:성인 1:소아
    RESERVE_NO NUMBER            NOT NULL,  -- 예약번호(FK)
    CONSTRAINT PK_TOUR     PRIMARY KEY(TOURIST_NO),
    CONSTRAINT FK_RES_TOUR FOREIGN KEY(RESERVE_NO) REFERENCES RESERVE_T(RESERVE_NO) ON DELETE CASCADE
);

CREATE TABLE PAYMENT_T (
    PAYMENT_NO   NUMBER NOT NULL,          -- 결제번호(PK)
    IMP_UID      VARCHAR2(30 BYTE)  NULL,  -- 결제고유번호
    PAY_YN       VARCHAR2(10 BYTE)  NULL,  -- 결제성공여부
    PAY_METHOD   VARCHAR2(30 BYTE)  NULL,  -- 결제수단
    PAID_AMOUNT  NUMBER             NULL,  -- 결제금액
    PAID_AT      VARCHAR2(30 BYTE)  NULL,  -- 결제승인시각
    MERCHANT_UID VARCHAR2(30 BYTE)  NULL,  -- 주문번호
    BUYER_NAME   VARCHAR2(20 BYTE)  NULL,  -- 구매자이름
    BUYER_EMAIL  VARCHAR2(100 BYTE) NULL,  -- 구매자이메일
    ERROR_MSG    VARCHAR2(300 BYTE) NULL,  -- 에러메시지
    PAY_STATUS   VARCHAR2(10 BYTE)  NULL,  -- 결제상태 ready,paid,failed(api응답으로 오는 값임)
    RESERVE_NO   NUMBER             NULL,  -- 예약번호(FK)
    CONSTRAINT PK_PAY PRIMARY KEY(PAYMENT_NO),
    CONSTRAINT FK_RES_PAY FOREIGN KEY(RESERVE_NO) REFERENCES RESERVE_T(RESERVE_NO) ON DELETE SET NULL
);